language: node_js
node_js:
  - 12.16.1

install:
  - yarn

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
        script:
          - yarn build
    - stage: test
        script:
          - yarn lint
          - yarn test
    - stage: publish
        script:
          - echo publish

cache:
  yarn: true
