language: node_js
node_js:
  - 12.16.1

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  - provider: script
    script: yarn semantic-release
    skip_cleanup: true
    on:
      branch: master

cache:
  yarn: true
