language: node_js
node_js:
  - 12.16.1

install:
  - yarn

stages:
  - build
  - test
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: build
        script:
          - yarn build
    - stage: test
        script:
          - yarn lint
          - yarn test
    - stage: publish
        script:
          - echo publish

cache:
  yarn: true

# Enable branch builds only for master
branches:
  only:
    - "master"
