language: node_js
node_js:
  - 12.16.1

install:
  - yarn

stages:
  - build
  - test
  - publish

jobs:
  include:
    script:
      - yarn lint
      - yarn test
      - yarn build

cache:
  yarn: true

branches:
  only:
    - master
