name: Release
on:
  push:
    branches:
    - main

env:
  HUSKY: 0 # Disable commit / push hooks when auto-publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v3
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
